# eslint Best Pratices rules enabled
# http://eslint.org/docs/rules/#best-practices
rules:
  accessor-pairs: 2 # http://eslint.org/docs/rules/accessor-pairs
  block-scoped-var: 2 # http://eslint.org/docs/rules/block-scoped-var
  complexity: 2 # http://eslint.org/docs/rules/complexity
  consistent-return: 2 # http://eslint.org/docs/rules/consistent-return
  curly: 2 # http://eslint.org/docs/rules/curly
  default-case: 2 # http://eslint.org/docs/rules/default-case
  dot-location: 2 # http://eslint.org/docs/rules/dot-location
  dot-notation: 2 # http://eslint.org/docs/rules/dot-notation
  eqeqeq: 2 # http://eslint.org/docs/rules/eqeqeq
  guard-for-in: 2 # http://eslint.org/docs/rules/guard-for-in
  no-alert: 2 # http://eslint.org/docs/rules/no-alert
  no-caller: 2 # http://eslint.org/docs/rules/no-caller
  no-div-regex: 2 # http://eslint.org/docs/rules/no-div-regex
  no-else-return: 2 # http://eslint.org/docs/rules/no-else-return
  no-empty-label: 2 # http://eslint.org/docs/rules/no-empty-label
  no-empty-pattern: 2 # http://eslint.org/docs/rules/no-empty-pattern
  no-eq-null: 2 # http://eslint.org/docs/rules/no-eq-null
  no-eval: 2 # http://eslint.org/docs/rules/no-eval
  no-extend-native: 2 # http://eslint.org/docs/rules/no-extend-native
  no-extra-bind: 2 # http://eslint.org/docs/rules/no-extra-bind
  no-fallthrough: 2 # http://eslint.org/docs/rules/no-fallthrough
  no-floating-decimal: 2 # http://eslint.org/docs/rules/no-floating-decimal
  no-implicit-coercion: 2 # http://eslint.org/docs/rules/no-implicit-coercion
  no-implied-eval: 2 # http://eslint.org/docs/rules/no-implied-eval
  no-invalid-this: 2 # http://eslint.org/docs/rules/no-invalid-this
  no-iterator: 2 # http://eslint.org/docs/rules/no-iterator
  no-labels: 2 # http://eslint.org/docs/rules/no-labels
  no-lone-blocks: 2 # http://eslint.org/docs/rules/no-lone-blocks
  no-loop-func: 2 # http://eslint.org/docs/rules/no-loop-func
  no-magic-numbers: 2 # http://eslint.org/docs/rules/no-magic-numbers
  no-multi-spaces: 2 # http://eslint.org/docs/rules/no-multi-spaces
  no-multi-str: 2 # http://eslint.org/docs/rules/no-multi-str
  no-native-reassign: 2 # http://eslint.org/docs/rules/no-native-reassign
  no-new-func: 2 # http://eslint.org/docs/rules/no-new-func
  no-new-wrappers: 2 # http://eslint.org/docs/rules/no-new-wrappers
  no-new: 2 # http://eslint.org/docs/rules/no-new
  no-octal-escape: 2 # http://eslint.org/docs/rules/no-octal-escape
  no-octal: 2 # http://eslint.org/docs/rules/no-octal
  no-param-reassign: 2 # http://eslint.org/docs/rules/no-param-reassign
  no-process-env: 2 # http://eslint.org/docs/rules/no-process-env
  no-proto: 2 # http://eslint.org/docs/rules/no-proto
  no-redeclare: 2 # http://eslint.org/docs/rules/no-redeclare
  no-return-assign: 2 # http://eslint.org/docs/rules/no-return-assign
  no-script-url: 2 # http://eslint.org/docs/rules/no-script-url
  no-self-compare: 2 # http://eslint.org/docs/rules/no-self-compare
  no-sequences: 2 # http://eslint.org/docs/rules/no-sequences
  no-throw-literal: 2 # http://eslint.org/docs/rules/no-throw-literal
  no-unused-expressions: 2 # http://eslint.org/docs/rules/no-unused-expressions
  no-useless-call: 2 # http://eslint.org/docs/rules/no-useless-call
  no-useless-concat: 2 # http://eslint.org/docs/rules/no-useless-concat
  no-void: 2 # http://eslint.org/docs/rules/no-void
  no-warning-comments: 2 # http://eslint.org/docs/rules/no-warning-comments
  no-with: 2 # http://eslint.org/docs/rules/no-with
  radix: 2 # http://eslint.org/docs/rules/radix
  vars-on-top: 2 # http://eslint.org/docs/rules/
  wrap-iife: 2 # http://eslint.org/docs/rules/wrap-iife
  yoda: 2 # http://eslint.org/docs/rules/yoda
